import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // カスタムサイドバー構成
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'インフラ',
      items: [{type: 'autogenerated', dirName: 'infrastructure'}],
    },
    {
      type: 'category',
      label: 'DWH',
      items: [
        {
          type: 'category',
          label: 'Snowflake',
          items: [{type: 'autogenerated', dirName: 'dwh/snowflake'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'アプリ',
      items: [{type: 'autogenerated', dirName: 'apps'}],
    },
    {
      type: 'category',
      label: 'BI',
      items: [{type: 'autogenerated', dirName: 'bi'}],
    },
    {
      type: 'category',
      label: '言語',
      items: [{type: 'autogenerated', dirName: 'languages'}],
    },
    {
      type: 'category',
      label: 'ドメイン情報',
      items: [{type: 'autogenerated', dirName: 'domain'}],
    },
    {
      type: 'category',
      label: 'その他',
      items: [{type: 'autogenerated', dirName: 'others'}],
    },
  ],
};

export default sidebars;
